import React from 'react';
import { AlertTriangle, ShieldCheck, RefreshCcw, Trash2, Download, ArrowRight } from 'lucide-react';
import { useApp } from '@/App';

const COPY = {
  ar: {
    title: 'ظهر تحذير "Google Play للحماية"؟',
    subtitle: 'لا تقلق — التطبيق آمن 100%. هذا التحذير سببه أن متصفح Chrome أنشأ نسخة قديمة من التطبيق على هاتفك. الحل:',
    step1Title: 'احذف التطبيق الحالي',
    step1: 'اضغط مطوّلاً على أيقونة BarberHub في شاشتك الرئيسية ← اختر "إلغاء التثبيت".',
    step2Title: 'امسح بيانات Chrome للموقع',
    step2: 'افتح Chrome ← القائمة ← الإعدادات ← إعدادات الموقع ← ابحث عن موقعنا ← احذف البيانات.',
    step3Title: 'أعد تثبيت التطبيق',
    step3: 'عد إلى الموقع في Chrome ← اضغط "تحميل التطبيق الآن" من جديد. سيتم إنشاء نسخة جديدة تدعم أحدث Android.',
    secureTitle: 'لماذا يحدث هذا؟',
    secureBody: 'تطبيقات الويب (PWA) يولّدها Chrome تلقائيًا على جهازك. لتجنّب التحذير نهائيًا، ينبغي نشر التطبيق عبر متجر Google Play الرسمي (ميزة قادمة قريبًا).',
    ok: 'فهمت، إغلاق',
  },
  en: {
    title: 'Got a "Google Play Protect" warning?',
    subtitle: 'Don\'t worry — the app is 100% safe. This happens because Chrome created an older version of the app on your phone. Fix:',
    step1Title: 'Uninstall current app',
    step1: 'Long-press the BarberHub icon on your home screen ← tap Uninstall.',
    step2Title: 'Clear Chrome site data',
    step2: 'Open Chrome ← Menu ← Settings ← Site settings ← find our site ← Clear data.',
    step3Title: 'Reinstall the app',
    step3: 'Return to the site in Chrome ← tap "Install App Now" again. A fresh version will be generated targeting the latest Android.',
    secureTitle: 'Why does this happen?',
    secureBody: 'PWAs are auto-generated by Chrome on your device. To remove the warning permanently, we will publish on Google Play Store soon.',
    ok: 'Got it, close',
  }
};

export default function InstallHelpModal({ open, onClose }) {
  const { language } = useApp() || { language: 'ar' };
  const t = COPY[language === 'ar' ? 'ar' : 'en'];

  if (!open) return null;

  return (
    <div
      className="fixed inset-0 z-[10000] bg-black/80 backdrop-blur-md flex items-center justify-center p-4 overflow-y-auto"
      role="dialog"
      aria-modal="true"
      onClick={onClose}
      data-testid="install-help-modal"
    >
      <div
        className="relative max-w-lg w-full bg-gradient-to-br from-[#1A120A] via-[#120A05] to-[#0A0605] border border-[#D4AF37]/40 rounded-3xl shadow-[0_20px_60px_rgba(212,175,55,0.3)] p-6 my-8"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-start gap-3 mb-5">
          <div className="w-12 h-12 rounded-full bg-gradient-to-br from-amber-500/30 to-red-500/20 border border-amber-500/40 flex items-center justify-center shrink-0">
            <AlertTriangle className="w-6 h-6 text-amber-400" />
          </div>
          <div className="flex-1">
            <h3 className="text-lg md:text-xl font-black text-[#F5D773] leading-tight">{t.title}</h3>
            <p className="text-[#F5D773]/70 text-sm mt-2 leading-relaxed">{t.subtitle}</p>
          </div>
        </div>

        {/* Steps */}
        <div className="space-y-3 mb-5">
          <Step n="1" title={t.step1Title} body={t.step1} icon={<Trash2 className="w-4 h-4" />} />
          <Step n="2" title={t.step2Title} body={t.step2} icon={<RefreshCcw className="w-4 h-4" />} />
          <Step n="3" title={t.step3Title} body={t.step3} icon={<Download className="w-4 h-4" />} />
        </div>

        {/* Why section */}
        <div className="bg-black/30 border border-[#D4AF37]/20 rounded-xl p-4 mb-5">
          <div className="flex items-center gap-2 mb-2">
            <ShieldCheck className="w-4 h-4 text-[#D4AF37]" />
            <span className="text-sm font-bold text-[#F5D773]">{t.secureTitle}</span>
          </div>
          <p className="text-xs text-[#F5D773]/60 leading-relaxed">{t.secureBody}</p>
        </div>

        {/* CTA */}
        <button
          onClick={onClose}
          className="w-full bg-gradient-to-r from-[#D4AF37] to-[#8B6914] text-[#0A0605] font-bold py-3.5 rounded-2xl flex items-center justify-center gap-2 hover:shadow-[0_8px_24px_rgba(212,175,55,0.4)] transition"
        >
          <ShieldCheck className="w-5 h-5" />
          {t.ok}
        </button>
      </div>
    </div>
  );
}

function Step({ n, title, body, icon }) {
  return (
    <div className="flex gap-3 bg-black/20 border border-[#D4AF37]/10 rounded-xl p-3">
      <div className="w-8 h-8 rounded-full bg-gradient-to-br from-[#D4AF37] to-[#8B6914] flex items-center justify-center text-[#0A0605] font-black text-sm shrink-0">
        {n}
      </div>
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2">
          <span className="text-[#F5D773] font-bold text-sm">{title}</span>
          <span className="text-[#D4AF37]/60">{icon}</span>
        </div>
        <p className="text-[#F5D773]/70 text-xs mt-1 leading-relaxed">{body}</p>
      </div>
    </div>
  );
}
